namespace P2PBank.Data.MicrosoftSql;

using Microsoft.Data.SqlClient;
using System.Text.RegularExpressions;
using System.Reflection;

using P2PBank.Data.Interface;

/// <summary>
/// Represents a SQL database.
/// </summary>
public class MicrosoftSqlDatabase : IDisposable
{
    /// <summary>
    /// Path to a SQL script for initializing the database tables.
    /// <\summary>
    public static string DATABASE_SQL = "P2PBank.Data.MicrosoftSql.database.sql";
    
    private SqlConnection connection;
    private MicrosoftSqlDatabaseConfig config;
    
    /// <summary>
    /// Opened SQL connection.
    /// </summary>
    public SqlConnection Connection {get => connection; }
    
    /// <summary>
    /// Connects to the database.
    /// </summary>
    /// <param name="credentials">The database credentials to log in with</param>
    /// <exception cref="SqlException">Thrown if the credentials are wrong</exception>
    public MicrosoftSqlDatabase(DatabaseConfig config)
    {
        MicrosoftSqlDatabaseConfig? mssqlConfig = config as MicrosoftSqlDatabaseConfig;
        if(mssqlConfig == null)
        {
            throw new Exception("MicrosoftSqlDatabase got an incompatable DatabaseConfig");
        }

        this.config = mssqlConfig;
        var conBuilder = this.config.ConnectionBuilder;
        
        connection = new SqlConnection(conBuilder.ConnectionString);
    }

    public void Connect()
    {
        connection.Open();
    }
    
    /// <summary>
    /// Creates a new database with the <see cref="DATABASE_SQL"/> file.
    /// </summary>
    /// <param name="credentials">The database credentials to log in with</param>
    /// <exception cref="DatabaseException"> Thrown if the database name is invalid</exception>
    /// <exception cref="SqlException">Thrown if the credentials are wrong</exception>
    public void Create()
    {
        var assembly = Assembly.GetExecutingAssembly();
        using var stream = assembly.GetManifestResourceStream(DATABASE_SQL);
        if(stream == null)
        {
            throw new Exception("failed to load database.sql");
        }
        using var reader = new StreamReader(stream);
        string sql = reader.ReadToEnd();

        
        var conBuilder = config.ConnectionBuilderNoDB;
        using(var connection = new SqlConnection(conBuilder.ConnectionString)) {
        connection.Open();
        
        // Regex generated by AI to stop SqlInjections
        // Very important for a school project that noone will try to attack
        if(!Regex.IsMatch(config.DatabaseName, @"^[a-zA-Z0-9_]+$"))
        {
            throw new Exception("Invalid database name");
        }

        var dbCommand = new SqlCommand($"CREATE DATABASE [{config.DatabaseName}]", connection);
        dbCommand.ExecuteNonQuery(); 
           
        }
        
        conBuilder = config.ConnectionBuilder;
        using(var connection = new SqlConnection(conBuilder.ConnectionString)) {
            connection.Open();
            
            var tableCommand= new SqlCommand(sql, connection);
            tableCommand.ExecuteNonQuery();
           
        }
    }
    
    /// <summary>
    /// Checks if the databse exists
    /// </sumary>
    /// <param name="credentials">The database credentials with the name of the database to check</param>
    /// <returns><c>true</c> if the database exists; otherwise, <c>false</c></returns>
    public bool Exists() 
    {
        try
        {
            var conBuilder = config.ConnectionBuilderNoDB;


            bool exists = true;
            using (var connection = new SqlConnection(conBuilder.ConnectionString))
            {
                connection.Open();
                using var command = new SqlCommand("SELECT name FROM sys.databases WHERE name = @name", connection);
                command.Parameters.AddWithValue("@name", config.DatabaseName);

                var reader = command.ExecuteScalar(); 
                if(reader == null) exists = false;
            }

            return exists;
        }
        catch
        {
            return false;
        }
    }
    
    /// <summary>
    /// Disposes the database connection.
    /// </summary>
    public void Dispose()
    {
        connection.Dispose();
    }

}