namespace Data;
using Microsoft.Data.SqlClient;
using System.Text.RegularExpressions;

/// <summary>
/// Represents a SQL database.
/// </summary>
public class Database : IDisposable
{
    /// <summary>
    /// Path to a SQL script for initializing the database tables.
    /// <\summary>
    public static string DATABASE_SQL = Path.Combine(AppContext.BaseDirectory, "database.sql");
    
    private SqlConnection connection;
    
    /// <summary>
    /// Opened SQL connection.
    /// </summary>
    public SqlConnection Connection {get => connection; }
    
    /// <summary>
    /// Connects to the database.
    /// </summary>
    /// <param name="credentials">The database credentials to log in with</param>
    /// <exception cref="SqlException">Thrown if the credentials are wrong</exception>
    public Database(DatabaseCredentials credentials)
    {
        var conBuilder = credentials.ConnectionBuilder;
        
        connection = new SqlConnection(conBuilder.ConnectionString);
        connection.Open();
    }
    
    /// <summary>
    /// Creates a new database with the <see cref="DATABASE_SQL"/> file.
    /// </summary>
    /// <param name="credentials">The database credentials to log in with</param>
    /// <exception cref="DatabaseException"> Thrown if the database name is invalid</exception>
    /// <exception cref="SqlException">Thrown if the credentials are wrong</exception>
    public static void Create(DatabaseCredentials credentials)
    {
        string sql = File.ReadAllText(DATABASE_SQL);
        
        var conBuilder = credentials.ConnectionBuilderNoDB;
        using(var connection = new SqlConnection(conBuilder.ConnectionString)) {
        connection.Open();
        
        // Regex generated by AI to stop SqlInjections
        // Very important for a school project that noone will try to attack
        if(!Regex.IsMatch(credentials.DatabaseName, @"^[a-zA-Z0-9_]+$"))
        {
            throw new DatabaseException("Invalid database name");
        }

        var dbCommand = new SqlCommand($"CREATE DATABASE [{credentials.DatabaseName}]", connection);
        dbCommand.ExecuteNonQuery(); 
           
        }
        
        conBuilder = credentials.ConnectionBuilder;
        using(var connection = new SqlConnection(conBuilder.ConnectionString)) {
            connection.Open();
            
            var tableCommand= new SqlCommand(sql, connection);
            tableCommand.ExecuteNonQuery();
           
        }
    }
    
    /// <summary>
    /// Checks if the databse exists
    /// </sumary>
    /// <param name="credentials">The database credentials with the name of the database to check</param>
    /// <returns><c>true</c> if the database exists; otherwise, <c>false</c></returns>
    public static bool Exists(DatabaseCredentials credentials) 
    {
        var conBuilder = credentials.ConnectionBuilderNoDB;
        
        bool exists = true;
        using (var connection = new SqlConnection(conBuilder.ConnectionString))
        {
            connection.Open();
            using var command = new SqlCommand("SELECT name FROM sys.databases WHERE name = @name", connection);
            command.Parameters.AddWithValue("@name", credentials.DatabaseName);

            var reader = command.ExecuteScalar(); 
            if(reader == null) exists = false;
        }

        return exists;
    }
    
    /// <summary>
    /// Disposes the database connection.
    /// </summary>
    public void Dispose()
    {
        connection.Dispose();
    }

}